현재 시간 출력하는 time now 추가
team-play-together/discord-bot pull request #4
Opened 2022-01-08 15:52 UTC by WraithKim

time now: 현재 시간을 UTC, PST, KST로 출력함.

now를 서브커맨드로 둔 건 time pst 같은 다른 서브커맨드도 둘 계획이기 때문.

module "luxon" 추가

luxon: timezone 처리를 편하게 하기 위한 모듈
원래 momentjs 설치하려다가.
https://momentjs.com/docs/#/-project-status/
이 글을 보고 luxon이 `Intl`를 지원해서 결정함.

2022-01-08 16:10 UTC, WraithKim commented on src/commands/time.ts
> +  + "PST: " + format(dateTime.setZone("America/Los_Angeles"));
이거 원래 `datetime.toUTC().format()` 같은 형태가 깔끔해 보여서 그렇게 바꾸고 싶었는데,
javascript에선 타입 강제가 아니라서 그런가 위에 처럼 쓰고 안에서 `dt` 대신 `this`로 바꿔도 되던데,
typescript에선 `this` 쓸 거면 `apply()` 아니면 안 됐음. 아님 내가 모르는 방법이 있나?

지금 보니까 그냥 이대로 놔둬도 되는 거 같다. 괜히 코드 이상하게 하려고 했던 거 같음.

2022-01-14 06:52 UTC, lyuha requested changes
서브커맨드에 대한 처리 필요.

그 외에는 부가 설명 정도

2022-01-14 06:52 UTC, lyuha commented on src/commands/time.ts
> +  + "PST: " + format(dateTime.setZone("America/Los_Angeles"));
js에서 this는 현재 실행 문맥인데, ts에서 this에 apply를 강제하는 이유는 현재 실행 문맥의 타입은 매우매우 까다로워서 apply로 고정하란 의미임.

2022-01-14 06:52 UTC, lyuha commented on src/commands/time.ts
> +      await interaction.reply(toFormat(now));
서브커맨드 처리하는 분기가 안 보인다. 서브커맨드가 당장 필요없으면 서브커맨드를 지울 것.

https://discordjs.guide/interactions/replying-to-slash-commands.html#subcommands

2022-01-19 01:27 UTC, WraithKim commented on src/commands/time.ts
> +      await interaction.reply(toFormat(now));
분기 안 넣은 건 실수.  
하지만 지금 서브커맨드가 필요한 게 아니니 지움.

2022-01-19 01:27 UTC, lyuha approved these changes

2022-01-19 01:28 UTC, lyuha commented
rebase & merge now

2022-01-19 01:34 UTC, merged